from __future__ import annotations

from pathlib import Path


MINIMAL_PDF = b"""%PDF-1.1
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 144]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length 65>>stream
BT /F1 10 Tf 16 96 Td (Fallback artifact generated by JobPilot) Tj ET
endstream endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000053 00000 n 
0000000109 00000 n 
0000000235 00000 n 
0000000350 00000 n 
trailer<</Size 6/Root 1 0 R>>
startxref
420
%%EOF
"""


def create_fallback_artifact(out_dir: Path, *, stem: str, reason: str, reason_code: str | None = None) -> dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = _next_available_path(out_dir, f"{stem}-fallback", ".pdf")
    pdf_path.write_bytes(MINIMAL_PDF)
    reason_path = pdf_path.with_suffix(".txt")
    reason_path.write_text(reason, encoding="utf-8")
    return {
        "pdf_path": str(pdf_path),
        "reason_path": str(reason_path),
        "reason_code": reason_code or "artifact_fallback",
    }


def ensure_fallback_pdf(out_dir: Path, *, stem: str, reason: str) -> Path:
    return Path(create_fallback_artifact(out_dir, stem=stem, reason=reason)["pdf_path"])


def _next_available_path(out_dir: Path, stem: str, suffix: str) -> Path:
    path = out_dir / f"{stem}{suffix}"
    if not path.exists():
        return path
    index = 2
    while True:
        candidate = out_dir / f"{stem}-{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1
